# ===================================================================
#  SPRING BOOT PROPERTIES
# ===================================================================


# ----------------------------------------
# PROFILES PROPERTIES
# ----------------------------------------
spring:
  profiles:
    active: #spring.profiles.active#
